on: [push, workflow_dispatch]
    
name: Find LaunchDarkly flag code references
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  launchDarklyCodeReferences:
    name: LaunchDarkly Code References
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      with:
        repository: launchdarkly/SupportService
        fetch-depth: 11
    - name: LaunchDarkly Code References
      uses: launchdarkly/find-code-references@a68d7da46aeffd66af43253b2d3619914508235b # main
      with:
        accessToken: ${{ secrets.LD_ACCESS_TOKEN }}
        debug: true
        ignoreServiceErrors: true
        projKey: support-service
        allowTags: true
        prune: true
